### ISSUE TITLE
He Called Himself Altruis

### ISSUE THREAD

**Issue by disastrous94** [NetherstormTeam/IssueTracker#347] opened 2016-05-29 20:24 UTC
You get this quest from _Huntress Kima_ and its flagged as group quest even if its not.

**Comment by Jiinkey** [comment] 2016-05-29 21:43
http://tbc.openwow.com/quest=9982

the whole questline is marked group because most of them requires group, this too is marked group, so it is intended and not a bug.

Closing.

**Closed by Jiinkey** 2016-05-29 21:43 UTC
Labels: Quest
