### ISSUE TITLE
[Spell/Mage] Blink is super wonky.

### ISSUE THREAD

**Issue by Clearlysql** [NetherstormTeam/IssueTracker#91] opened 2016-04-23 13:35 UTC
Blink will teleport you under textures in certain areas such as Undercity (The Canals to be specific). I assume this has something to do with the fact that it snaps you back to the ground after blinking.

**Comment by Blumfield** [comment] 2016-04-23 15:21
A fix has been commited, i'm not closing it yet, we'll need feedback once it's live on PTR

**Comment by Clearlysql** [comment] 2016-04-23 15:22
Will test thoroughly once fix is live.

**Comment by Nevarian** [comment] 2016-04-24 18:59
Cannot reproduce anymore.

**Closed by Nevarian** 2016-04-24 18:59 UTC
Labels: confirmed, high priority, spell
