### ISSUE TITLE
Elemental Mastery

### ISSUE THREAD

**Issue by nstracker** [NetherstormTeam/IssueTracker#80] opened 2016-04-23 00:41 UTC
As for the Elemental Mastery, Elemental Shaman Talent, it seems to not always provide 100% critical strike as the tooltip says, I have seen multiple times tonight where it did not crit with a Lightning Bolt after using Elemental Mastery, I can&#39;t exactly say how, when or what I did to produce the issue, but I have noticed it multiple times over the course of the night.

-Ophius

**Comment by Blumfield** [comment] 2016-04-23 21:32
I cannot reproduce it, tested 20 times in a row, I always crit

needs to be investigated

**Comment by JppTheInsane** [comment] 2016-04-24 01:31
Same.

Even checked if a dot could be consuming the crit, but still no luck.

**Comment by Blumfield** [comment] 2016-04-26 16:21
I tried again, cannot be reproduced, closing the issue

**Closed by Blumfield** 2016-04-26 16:21 UTC
Labels: Needs confirmation, spell
